image: golang:latest

stages:
  - build

building:
  stage: build
  script:
    - go get -u github.com/pepa65/fail2drop
    - GOOS=linux GOARCH=amd64 go build -ldflags="-s -w"
    - GOOS=linux GOARCH=arm go build -ldflags="-s -w" -o fail2drop_pi
  artifacts:
    name: fail2drop
    paths:
     - fail2drop
     - fail2drop_pi
