upx:
  - enabled: true
    compress: best
    goos: [linux]

archives:
  - format: binary

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
